In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.cross_validation import train_test_split
from sklearn.metrics import precision_score

C:\Users\CS210\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [8]:
from keras.models import Sequential
from keras.layers import Activation
from keras.optimizers import SGD
from keras.layers import Dense
from keras.utils import np_utils

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
from matplotlib import pyplot as plt

In [11]:
import seaborn as sns

In [12]:
import graphviz # anaconda prompt- pip install graphviz

import pydotplus

In [13]:
import pydotplus # anaconda prompt- pip install pydotplus

In [14]:
import io 
from scipy import misc
%matplotlib inline

In [15]:
# Make results reproducible
seed = 1234
np.random.seed(seed)
tf.set_random_seed(seed)

In [16]:
file = '../../input/drug_data.csv'
dataset = pd.read_csv(file, 'rb', delimiter =';')

In [17]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df = pd.DataFrame(dataset)
cols = df.columns[1:13]
for col in cols:
    le.fit(dataset[col])
    dataset[col] = le.transform(dataset[col])

In [18]:
cols = df.columns[13:]
for col in cols:
    dataset[col] = dataset[col].str.replace('CL','').astype(int)    

In [19]:
cols = df.columns[13:]
for col in cols:
    if col != 'Chocolate':
        df.__delitem__(col)
      

In [20]:
dataset = pd.get_dummies(dataset, columns=['Chocolate']) # One Hot Encoding
values = list(dataset.columns.values)
values

['ID',
 'Age',
 'Gender',
 'Education',
 'Country',
 'Ethnicity',
 'Nscore',
 'Escore',
 'Oscore',
 'Ascore',
 'Cscore',
 'Impulsive',
 'SS',
 'Chocolate_0',
 'Chocolate_1',
 'Chocolate_2',
 'Chocolate_3',
 'Chocolate_4',
 'Chocolate_5',
 'Chocolate_6']

In [21]:
y = dataset[values[13:]]
y = np.array(y, dtype='float32')
y

array([[ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]], dtype=float32)

In [22]:
X = dataset[values[1:13]]
X = np.array(X, dtype='float32')
X

array([[  2.,   1.,   0., ...,   0.,   0.,   3.],
       [  0.,   0.,   8., ...,   1.,   1.,   0.],
       [  2.,   0.,   0., ...,   8.,   2.,   7.],
       ..., 
       [  0.,   1.,   6., ...,  11.,   5.,   1.],
       [  1.,   1.,   1., ...,  20.,   7.,   9.],
       [  1.,   0.,   1., ...,  27.,   6.,   9.]], dtype=float32)

In [23]:
# Shuffle Data
indices = np.random.choice(len(X), len(X), replace=False)
X_values = X[indices]
y_values = y[indices]



X_train, X_test = train_test_split(X_values, test_size = 0.20)
y_train, y_test = train_test_split(y_values, test_size = 0.20)


# Creating a Train and a Test Dataset
test_size = 377
#X_test = X_values[-test_size:]
#X_train = X_values[:-test_size]
#y_test = y_values[-test_size:]
#y_train = y_values[:-test_size]


In [24]:
# define the architecture of the network
model = Sequential()
model.add(Dense(768, input_dim=12, init="uniform",
	activation="relu"))
model.add(Dense(384, init="uniform", activation="relu"))
model.add(Dense(7))
model.add(Activation("softmax"))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 768)               9984      
_________________________________________________________________
dense_2 (Dense)              (None, 384)               295296    
_________________________________________________________________
dense_3 (Dense)              (None, 7)                 2695      
_________________________________________________________________
activation_1 (Activation)    (None, 7)                 0         
Total params: 307,975
Trainable params: 307,975
Non-trainable params: 0
_________________________________________________________________


C:\Users\CS210\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(768, input_dim=12, activation="relu", kernel_initializer="uniform")`
  after removing the cwd from sys.path.
C:\Users\CS210\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(384, activation="relu", kernel_initializer="uniform")`
  """


In [27]:
# train the model using SGD
print("[INFO] compiling model...")
sgd = SGD(lr=0.01)
model.compile(loss="binary_crossentropy", optimizer=sgd,
	metrics=["accuracy"])
model.fit(X_train, y_train, epochs=50, batch_size=64,
	verbose=1)

[INFO] compiling model...
Epoch 1/50
1508/1508 [==============================] - 0s 177us/step - loss: 0.2821 - acc: 0.8609
Epoch 2/50
1508/1508 [==============================] - 0s 67us/step - loss: 0.2809 - acc: 0.8638
Epoch 3/50
1508/1508 [==============================] - 0s 74us/step - loss: 0.2803 - acc: 0.8650
Epoch 4/50
1508/1508 [==============================] - 0s 68us/step - loss: 0.2804 - acc: 0.8630
Epoch 5/50
1508/1508 [==============================] - 0s 67us/step - loss: 0.2814 - acc: 0.8630
Epoch 6/50
1508/1508 [==============================] - 0s 72us/step - loss: 0.2810 - acc: 0.8626
Epoch 7/50
1508/1508 [==============================] - 0s 68us/step - loss: 0.2805 - acc: 0.8628
Epoch 8/50
1508/1508 [==============================] - 0s 73us/step - loss: 0.2813 - acc: 0.8642
Epoch 9/50
1508/1508 [==============================] - 0s 71us/step - loss: 0.2804 - acc: 0.8657
Epoch 10/50
1508/1508 [==============================] - 0s 68us/step - loss: 0.2806 - acc:

In [29]:
# show the accuracy on the testing set
print("[INFO] evaluating on testing set...")
(loss, accuracy) = model.evaluate(X_test, y_test,
	batch_size=128, verbose=1)
print("[INFO] loss={:.4f}, accuracy: {:.4f}%".format(loss,
	accuracy * 100))

[INFO] evaluating on testing set...
377/377 [==============================] - 0s 24us/step
[INFO] loss=0.3045, accuracy: 83.7059%


In [33]:
from sklearn.metrics import classification_report

history = model.fit(X_train, y_train, batch_size=32, epochs=10, verbose=1, validation_data=(X_test, y_test), shuffle=True)

Train on 1508 samples, validate on 377 samples
Epoch 1/10
1508/1508 [==============================] - 0s 141us/step - loss: 0.2750 - acc: 0.8677 - val_loss: 0.2989 - val_acc: 0.8484
Epoch 2/10
1508/1508 [==============================] - 0s 132us/step - loss: 0.2743 - acc: 0.8679 - val_loss: 0.2987 - val_acc: 0.8507
Epoch 3/10
1508/1508 [==============================] - 0s 135us/step - loss: 0.2745 - acc: 0.8676 - val_loss: 0.2976 - val_acc: 0.8534
Epoch 4/10
1508/1508 [==============================] - 0s 137us/step - loss: 0.2737 - acc: 0.8679 - val_loss: 0.3013 - val_acc: 0.8473
Epoch 5/10
1508/1508 [==============================] - 0s 137us/step - loss: 0.2739 - acc: 0.8669 - val_loss: 0.3289 - val_acc: 0.8420
Epoch 6/10
1508/1508 [==============================] - 0s 130us/step - loss: 0.2746 - acc: 0.8695 - val_loss: 0.3146 - val_acc: 0.8412
Epoch 7/10
1508/1508 [==============================] - 0s 135us/step - loss: 0.2733 - acc: 0.8667 - val_loss: 0.3008 - val_acc: 0.8454
E

In [62]:
pred = model.predict(X_test, batch_size=32, verbose=1)
predicted = np.argmax(pred, axis=1)
predicted
actual = []
for elm in y_test:
    for i in range(len(elm)):
        if(elm[i] == 1.0):
            actual.append(i)
print(actual)
print(predicted)
precision_score(actual, predicted, average=None)
#report = classification_report(np.argmax(y_test, axis=1), predicted)
#print(report)

377/377 [==============================] - 0s 48us/step
[5, 6, 5, 6, 6, 6, 5, 6, 6, 4, 6, 6, 5, 6, 5, 0, 6, 5, 5, 4, 5, 5, 6, 6, 5, 4, 6, 5, 3, 5, 5, 6, 5, 5, 4, 5, 5, 6, 5, 4, 5, 6, 6, 4, 6, 5, 6, 6, 4, 6, 5, 4, 4, 5, 6, 2, 6, 5, 6, 6, 6, 3, 6, 6, 5, 6, 5, 5, 5, 6, 4, 6, 6, 4, 4, 4, 4, 6, 3, 4, 6, 6, 5, 6, 6, 5, 6, 4, 5, 6, 5, 4, 4, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5, 6, 4, 5, 6, 4, 5, 6, 5, 6, 4, 5, 4, 5, 4, 6, 4, 3, 4, 6, 6, 6, 6, 6, 6, 3, 6, 5, 3, 6, 6, 5, 3, 6, 5, 4, 6, 5, 6, 6, 6, 5, 4, 5, 5, 4, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 3, 4, 5, 5, 6, 5, 6, 4, 6, 6, 5, 5, 4, 6, 6, 6, 6, 5, 6, 6, 5, 5, 4, 6, 6, 5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 3, 6, 5, 5, 5, 5, 6, 4, 4, 0, 5, 5, 5, 6, 6, 5, 2, 6, 5, 3, 5, 6, 6, 4, 4, 5, 4, 5, 6, 5, 0, 6, 5, 6, 4, 4, 6, 0, 5, 5, 5, 5, 5, 5, 4, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 3, 5, 3, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 4, 5, 6, 6, 5, 6, 5, 6, 5, 4, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 4, 6, 6, 6, 3, 6, 6, 5, 5, 5, 4, 5, 5, 4, 6

C:\Users\CS210\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.35051546,
        0.47058824])